### ISSUE TITLE
Shrines act 3-5

### ISSUE THREAD

**Issue by RushTheOne** [jcageman/d2mapapi#13]
MapApi does not appear to pass object data specifically for shrines in acts 3-5.  Any ideas?

**Comment by jcageman** [comment]
I've checked this and i notice the same thing. It's weird, because shrines are just "objects" and the code is checking them all.
Even analyzing the packets I've noticed that shrines are really not in the output of the map API. I've checked the location according to diablo itself based on the packets and there is no object on those locations according to the map API. I've not needed them before, so  didn't really notice it. You could check some other implementations, maybe there is a bug in my code.
